// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcSample.Repositories.EFDbContext
{
    public partial class Customers
    {
        public Guid Custid { get; set; }
        public string Custnm { get; set; }
        public string Contactnum { get; set; }
        public string Perosnalid { get; set; }
    }
}