// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MvcSample.Repositories.EFDbContext
{
    public partial class CustomerInfoContext : DbContext
    {
        public CustomerInfoContext()
        {
        }

        public CustomerInfoContext(DbContextOptions<CustomerInfoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Customers> Customers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customers>(entity =>
            {
                entity.HasKey(e => e.Custid)
                    .HasName("PK_customers");

                entity.Property(e => e.Custid)
                    .ValueGeneratedNever()
                    .HasColumnName("custid");

                entity.Property(e => e.Contactnum)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("contactnum");

                entity.Property(e => e.Custnm)
                    .HasMaxLength(50)
                    .HasColumnName("custnm");

                entity.Property(e => e.Perosnalid)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("perosnalid");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}